export const keywords = [
    "Cooperativa Ayllus Perú",
    "Ahorros y créditos Ayacucho",
    "Cooperativa de ahorro y crédito",
    "Superintendencia de Banca, Seguros y AFP",
    "Superintendencia Adjunta de Cooperativas",
    "Fondo de Seguro de Depósito Cooperativo (FSDC)",
    "Resolución SBS N° 5061-2018",
    "Registro COOPAC",
    "Resolución SBS N° 4977-2018",
    "Procedimiento N° 178 del TUPA",
    "Registro N° 212-2019-REG.COOPAC-SBS",
    "Ahorros seguros Ayacucho",
    "Créditos accesibles Ayacucho",
    "Servicios financieros Ayacucho",
    "Cooperativa regulada SBS",
    "Supervisión de cooperativas",
    "Ahorros cooperativos Perú",
    "Préstamos cooperativos Ayacucho",
    "Cooperativa financiera Ayacucho",
    "Seguridad financiera cooperativa",
    "Beneficios cooperativos Ayacucho",
    "Servicios de ahorro y crédito",
    "Financiamiento cooperativo Ayacucho",
    "Soluciones financieras Ayacucho",
    "Comunidad cooperativa Ayacucho"
];
